chore: add license, contribution, clippy
hopeyen/indexer-service-rs pull request #13
Opened 2023-07-20 13:36 UTC by hopeyen

2023-07-20 17:35 UTC, aasseman requested changes
In general, I'd prefer not lump 3 different things into one commit/PR. I've already assigned myself on some of the CI related things

2023-07-20 17:44 UTC, aasseman commented on .cargo/config.toml
> +rustflags = ["-A", "dead_code"]
Or perhaps is it just temporary while we're building out the functionality?

2023-07-20 23:11 UTC, hopeyen commented on .cargo/config.toml
> +rustflags = ["-A", "dead_code"]
My preference is for this to be temporary, but am also fine to add it at specific places. I've removed it for now so it can be more intentional

2023-07-20 23:12 UTC, hopeyen commented
Thanks for the review! I've updated the PR to only add the docs and left the CI alone 🙏

2023-07-21 21:48 UTC, aasseman approved these changes
:shipit: 
Sorry for the delay :sweat_smile:

2023-07-24 17:23 UTC, merged